# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/exp4',
                'doc_host': 'https://caioatila.github.io',
                'git_url': 'https://github.com/caioatila/exp4',
                'lib_path': 'exp4'},
  'syms': {'exp4\\core': {'exp4\\core.foo': ('core.html#foo', 'exp4\\core.py')}}}