# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/exp4',
                'doc_host': 'https://caioatila.github.io',
                'git_url': 'https://github.com/caioatila/exp4',
                'lib_path': 'exp4'},
  'syms': { 'exp4\\core': { 'exp4\\core.geo2buffer': ('core.html#geo2buffer', 'exp4\\core.py'),
                            'exp4\\core.get_date': ('core.html#get_date', 'exp4\\core.py'),
                            'exp4\\core.load_relato': ('core.html#load_relato', 'exp4\\core.py'),
                            'exp4\\core.replace_val': ('core.html#replace_val', 'exp4\\core.py')},
            'exp4\\dataset': {}}}